package art.arcane.iris.engine.object;

import art.arcane.iris.engine.object.annotations.Desc;
import art.arcane.iris.engine.object.annotations.MinNumber;
import art.arcane.iris.engine.object.annotations.RegistryListVanillaStructure;
import art.arcane.iris.engine.object.annotations.Required;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Data
@Desc("A live vanilla, datapack, or modded structure generated by Minecraft at an Iris-controlled placement.")
public class IrisNativeStructure {
    @Required
    @RegistryListVanillaStructure
    @Desc("Registered structure key. The source retains its native generator, pieces, templates, processors, entities, markers, and data.")
    private String structure = "";

    @MinNumber(1)
    @Desc("Relative selection weight when a placement offers multiple native structure sources.")
    private int weight = 1;

    @Desc("Optional jigsaw-only assembly overrides. Null preserves the complete registered structure definition.")
    private IrisJigsawConfiguration jigsaw = null;
}
